MVC/Controllers/EnvioComunController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Models.Envios;
using MVC.Models.Usuarios;
using Newtonsoft.Json;

namespace MVC.Controllers
{
    public class EnvioComunController : Controller
    {
        private string url = "";
        private string urlBase = "/api/";

        public EnvioComunController(IConfiguration configuration)
        {
            urlBase = configuration.GetValue<string>("url");
            url = urlBase + "Envio/";
        }

		// GET: EnvioComunController/BuscarPorTracking
		public ActionResult BuscarPorTracking()
		{
			return View();
		}

		// POST: EnvioComunController/BuscarPorTracking
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult BuscarPorTracking(EnvioTrackingViewModel model)
		{
			if (!ModelState.IsValid)
			{
				return View(model);
			}

			try
			{
				HttpClient cliente = new HttpClient();
				Task<HttpResponseMessage> tarea = cliente.GetAsync(url + model.codTracking);
				tarea.Wait();

				HttpResponseMessage respuesta = tarea.Result;

				if (!respuesta.IsSuccessStatusCode)
				{
					ViewBag.Mensaje = "No se encontró el envío con ese código";
					return View(model);
				}

				HttpContent contenido = respuesta.Content;
				Task<string> body = contenido.ReadAsStringAsync();
				body.Wait();
				string datos = body.Result;

				var envio = JsonConvert.DeserializeObject<DatoEnvioCompletoViewModel>(datos);
				return View("DetallesEnvio", envio);
			}
			catch (Exception ex)
			{
				ViewBag.Mensaje = $"Error al buscar: {ex.Message}";
				return View(model);
			}
		}

		// GET: EnvioComunController/DetallesEnvio
		public ActionResult DetallesEnvio(DatoEnvioCompletoViewModel model)
		{
			return View(model);
		}

        [HttpGet]
        public IActionResult ListarEnviosDeCliente()
        {
            List<EnvioClienteViewModel> vm = new List<EnvioClienteViewModel>();
            try
            {
                string email = HttpContext.Session.GetString("EmailUsuario");
                HttpClient cliente = new HttpClient();
                cliente.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                Task<HttpResponseMessage> tarea = cliente.GetAsync(url + "email" + email);
                tarea.Wait();
                HttpResponseMessage respuesta = tarea.Result;
                HttpContent contenido = respuesta.Content;
                Task<string> body = contenido.ReadAsStringAsync();
                body.Wait();
                string datos = body.Result;
                if (respuesta.IsSuccessStatusCode)
                {
                    vm = JsonConvert.DeserializeObject<List<EnvioClienteViewModel>>(datos);
                }
                else
                {
                    ViewBag.Mensaje = datos;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Hubo un error.";
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult ListarComentariosDeEnvio(int id)
        {
            List<ComentarioCompletoViewModel> vm = new List<ComentarioCompletoViewModel>();
            try
            {
                string email = HttpContext.Session.GetString("EmailUsuario");
                HttpClient cliente = new HttpClient();
                cliente.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                Task<HttpResponseMessage> tarea = cliente.GetAsync(url + "email/" + email + "envio/" + id);
                tarea.Wait();
                HttpResponseMessage respuesta = tarea.Result;
                HttpContent contenido = respuesta.Content;
                Task<string> body = contenido.ReadAsStringAsync();
                body.Wait();
                string datos = body.Result;
                if (respuesta.IsSuccessStatusCode)
                {
                    vm = JsonConvert.DeserializeObject<List<ComentarioCompletoViewModel>>(datos);
                }
                else
                {
                    ViewBag.Mensaje = datos;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Hubo un error.";
            }
            return View(vm);
        }

        public IActionResult FiltrarEnviosPorFecha()
        {
            return View();
        }

        public IActionResult ListarEnviosPorFecha(DateTime desde, DateTime hasta, string? estado)
        {
            List<EnvioClienteViewModel> vm = new List<EnvioClienteViewModel>();
            try
            {
                string email = HttpContext.Session.GetString("EmailUsuario");
                HttpClient cliente = new HttpClient();
                cliente.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                string desdeReal = desde.ToShortDateString().Replace("/", "-");
                string hastaReal = hasta.ToShortDateString().Replace("/", "-");
                Task<HttpResponseMessage> tarea = cliente.GetAsync(url + "email/" + email + "desde/" + desdeReal + "hasta/" + hastaReal + "estado/" + estado);
                tarea.Wait();
                HttpResponseMessage respuesta = tarea.Result;
                HttpContent contenido = respuesta.Content;
                Task<string> body = contenido.ReadAsStringAsync();
                body.Wait();
                string datos = body.Result;
                if (respuesta.IsSuccessStatusCode)
                {
                    vm = JsonConvert.DeserializeObject<List<EnvioClienteViewModel>>(datos);
                }
                else
                {
                    ViewBag.Mensaje = datos;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Hubo un error.";
            }
            return View(vm);
        }

        public IActionResult FiltrarEnviosPorComentario()
        {
            return View();
        }

        public IActionResult ListarEnviosPorComentario(string comentario)
        {
            List<EnvioClienteViewModel> vm = new List<EnvioClienteViewModel>();
            try
            {
                string email = HttpContext.Session.GetString("EmailUsuario");
                HttpClient cliente = new HttpClient();
                cliente.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
                Task<HttpResponseMessage> tarea = cliente.GetAsync(url + "email/" + email + "palabra/" + comentario);
                tarea.Wait();
                HttpResponseMessage respuesta = tarea.Result;
                HttpContent contenido = respuesta.Content;
                Task<string> body = contenido.ReadAsStringAsync();
                body.Wait();
                string datos = body.Result;
                if (respuesta.IsSuccessStatusCode)
                {
                    vm = JsonConvert.DeserializeObject<List<EnvioClienteViewModel>>(datos);
                }
                else
                {
                    ViewBag.Mensaje = datos;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "Hubo un error.";
            }
            return View(vm);
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MVC</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						@if (Context.Session.GetString("rol") != null)
						{
							@if (Context.Session.GetString("rol") == "Administrador")
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Empleados</a>
								</li>
							}
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="EnvioComun" asp-action="Index">Envios</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
							</li>
						}
						else
						{
							if (Context.Session.GetString("NombreUsuario") != null)
							{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="EnvioComun" asp-action="ListarEnviosDeCliente">Envios</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="EnvioComun" asp-action="FiltrarEnviosPorFecha">Filtrar envios por fecha</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="EnvioComun" asp-action="FiltrarEnviosPorComentario">Filtrar envios por seguimiento</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword">Cambiar contraseña</a>
								</li>
							}
							else
							{

								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
								</li>
							}
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="EnvioComun" asp-action="BuscarPorTracking">Buscar por tracking</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>